services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - BASE_URL=http://host.docker.internal:7189
    extra_hosts:
      - "host.docker.internal:host-gateway"   